"use client";

import { useMemo, useState } from "react";
import { filterRelationships, scopedRelationships, type Direction, type ExplorerData, type ExplorerRelationship, type RelationshipSource } from "./explorer-data.js";
import { relationshipGraph } from "./relationship-graph-model.js";

export default function RelationshipExplorer({ data }: { data: ExplorerData }) {
  const [query, setQuery] = useState("");
  const [scope, setScope] = useState<"shop" | "all">("all");
  const [source, setSource] = useState<RelationshipSource | "all">("all");
  const [direction, setDirection] = useState<Direction>("all");
  const [selectedTable, setSelectedTable] = useState(data.tables[0]?.id ?? data.shopMap.anchor.tableId);
  const [selectedEdge, setSelectedEdge] = useState<ExplorerRelationship | null>(null);
  const normalizedQuery = query.trim().toLowerCase();
  const scopeIds = useMemo(() => new Set(data.shopMap.nodes.map((node) => node.tableId)), [data.shopMap.nodes]);
  const tables = data.tables.filter((table) => scope === "all" || scopeIds.has(table.id));
  const visibleTables = tables.filter((table) => !normalizedQuery || `${table.name} ${table.id}`.toLowerCase().includes(normalizedQuery));
  const relationships = scopedRelationships(scope, data.relationships, data.shopMap.edges);
  const visibleEdges = useMemo(() => filterRelationships(relationships, source, direction, selectedTable), [direction, relationships, selectedTable, source]);
  const selectedNode = data.tables.find((table) => table.id === selectedTable) ?? data.tables[0];
  const sourceCounts = { ninox: data.relationships.filter((edge) => edge.source === "ninox").length, detected: data.relationships.filter((edge) => edge.source === "detected").length, unknown: data.relationships.filter((edge) => edge.source === "unknown").length };
  const changeScope = (next: "all" | "shop") => { setScope(next); if (next === "shop" && !scopeIds.has(selectedTable)) setSelectedTable(data.shopMap.anchor.tableId); setSelectedEdge(null); };
  const graph = useMemo(() => relationshipGraph(selectedTable, selectedNode?.name ?? "Unknown", visibleEdges), [selectedNode?.name, selectedTable, visibleEdges]);
  const selectNeighbor = (id: string) => { setSelectedTable(id); setSelectedEdge(null); };
  return <main className="shell">
    <header className="topbar"><div><div className="eyebrow">NINOX DATA MAPPER / P0</div><h1>Relationship Explorer</h1><p className="subhead">Browse every table and relationship in the local database.</p></div><div className="readonly"><span className="status-dot" /> READ ONLY</div></header>
    <section className="hero-grid"><div className="database-card"><div className="card-label">DATABASE SCOPE</div><div className="database-name">Complete Ninox database</div><div className="database-note">{data.summary.tableCount} tables · {data.summary.relationshipCount} relationships</div></div><div className="metric-card"><span>TABLES</span><strong>{data.summary.tableCount}</strong><small>all scanned tables</small></div><div className="metric-card"><span>RELATIONSHIPS</span><strong>{data.summary.relationshipCount}</strong><small>global graph edges</small></div><div className="metric-card"><span>HYPOTHESES</span><strong className="amber">{sourceCounts.detected}</strong><small>detected, review required</small></div></section>
    <section className="workspace"><aside className="sidebar"><div className="section-heading"><span>{scope === "all" ? "ALL TABLES" : "TRUCKSDB AREA"}</span><em>{visibleTables.length} / {tables.length}</em></div><input aria-label="Search tables" placeholder="Search tables..." value={query} onChange={(event) => setQuery(event.target.value)} /><div className="scope-control" role="group" aria-label="Database scope"><button className={scope === "all" ? "selected" : ""} aria-pressed={scope === "all"} onClick={() => changeScope("all")}>All database</button><button className={scope === "shop" ? "selected" : ""} aria-pressed={scope === "shop"} onClick={() => changeScope("shop")}>TrucksDB area</button></div><div className="table-list">{visibleTables.map((table) => <button className={`table-row ${selectedTable === table.id ? "active" : ""}`} key={table.id} onClick={() => { setSelectedTable(table.id); setSelectedEdge(null); }}><span className="node-mark" /><span><b>{table.name}</b><small>{table.id} · {table.relationshipCount} relationship{table.relationshipCount === 1 ? "" : "s"}</small></span><span className="chevron">›</span></button>)}</div></aside>
      <section className="content"><div className="content-header"><div><div className="card-label">SELECTED TABLE</div><h2>{selectedNode?.name ?? "Unknown"}</h2><span className="pill">ID {selectedNode?.id}</span></div><div className="legend"><span><i className="legend-dot green" /> Ninox <b>{sourceCounts.ninox}</b></span><span><i className="legend-dot amber-dot" /> Detected <b>{sourceCounts.detected}</b></span><span><i className="legend-dot gray" /> Unknown <b>{sourceCounts.unknown}</b></span></div></div>
        <div className="filters"><label>Source <select aria-label="Source filter" value={source} onChange={(event) => setSource(event.target.value as RelationshipSource | "all")}><option value="all">All</option><option value="ninox">Ninox</option><option value="detected">Detected</option><option value="unknown">Unknown</option></select></label><label>Direction <select aria-label="Direction filter" value={direction} onChange={(event) => setDirection(event.target.value as Direction)}><option value="all">All</option><option value="incoming">Incoming</option><option value="outgoing">Outgoing</option></select></label></div>
        <section className="graph-panel" aria-labelledby="graph-heading"><div className="graph-heading"><div><div className="card-label">RELATIONSHIP GRAPH</div><h3 id="graph-heading">Direct neighbors</h3></div><span className="muted">{graph.edges.length} visible edge{graph.edges.length === 1 ? "" : "s"}</span></div><div className="graph-legend" aria-label="Graph relationship legend"><span className="ninox">Ninox</span><span className="detected">Hypothesis</span><span className="unknown">Unknown</span></div>{graph.neighbors.length === 0 ? <div className="graph-empty">No direct relationships match these filters.</div> : <svg className="relationship-graph" viewBox="0 0 760 560" role="img" aria-labelledby="graph-title graph-desc"><title id="graph-title">Relationships centered on {selectedNode?.name ?? "Unknown"}</title><desc id="graph-desc">Filtered direct neighbors and relationship edges. Orange dashed edges are hypotheses.</desc>{graph.edges.map((edge, index) => { const targetId = edge.sourceTableId === selectedTable ? edge.targetTableId : edge.sourceTableId; const target = graph.neighbors.find((node) => node.id === targetId)!; const parallel = graph.edges.filter((candidate) => (candidate.sourceTableId === selectedTable ? candidate.targetTableId : candidate.sourceTableId) === targetId); const parallelIndex = parallel.indexOf(edge); const offset = (parallelIndex - (parallel.length - 1) / 2) * 8; const length = Math.hypot(target.x - graph.center.x, target.y - graph.center.y) || 1; const offsetX = (target.y - graph.center.y) / length * offset; const offsetY = (graph.center.x - target.x) / length * offset; return <g key={`${edge.sourceTableId}-${edge.sourceFieldId}-${edge.targetTableId}-${index}`} className={`graph-edge ${edge.source}`}><title>{edge.source === "detected" ? "Hypothesis" : edge.source}: {edge.sourceTable}.{edge.sourceField} to {edge.targetTable}.{edge.targetField}</title><line x1={graph.center.x + offsetX} y1={graph.center.y + offsetY} x2={target.x + offsetX} y2={target.y + offsetY} /></g>; })}<g className="graph-center"><title>{graph.center.name}</title><circle cx={graph.center.x} cy={graph.center.y} r="42" /><text x={graph.center.x} y={graph.center.y - 2}>{graph.center.label}</text><text x={graph.center.x} y={graph.center.y + 14}>{graph.center.id}</text></g>{graph.neighbors.map((node) => <g className="graph-neighbor" key={node.id} role="button" tabIndex={0} aria-label={`Select ${node.name}`} onClick={() => selectNeighbor(node.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); selectNeighbor(node.id); } }}><title>{node.name}</title><circle cx={node.x} cy={node.y} r="30" /><text x={node.x} y={node.y - 2}>{node.label}</text><text x={node.x} y={node.y + 14}>{node.id}</text></g>)}</svg>}</section>
        <div className="relation-list">{visibleEdges.length === 0 && <div className="empty">No relationships match these filters.</div>}{visibleEdges.map((edge, index) => <button className={`relation-card ${selectedEdge === edge ? "selected" : ""}`} key={`${edge.sourceTableId}-${edge.sourceFieldId}-${edge.targetTableId}-${index}`} onClick={() => setSelectedEdge(edge)}><div className="relation-direction"><span className={`relation-icon ${edge.source === "ninox" ? "green-bg" : "amber-bg"}`}>{edge.source === "ninox" ? "✓" : "•"}</span><span>{edge.sourceTableId === selectedTable ? "OUTGOING" : "INCOMING"}</span></div><div className="relation-main"><strong>{edge.sourceTable}.{edge.sourceField}</strong><span className="arrow">→</span><strong>{edge.targetTable}.{edge.targetField}</strong></div><div className="relation-meta"><span>{edge.source === "detected" ? "Hypothesis" : edge.source}</span><span>{Math.round(edge.confidence * 100)}% confidence</span></div></button>)}</div>
        <div className="detail-panel"><div className="card-label">RELATIONSHIP DETAIL</div>{selectedEdge ? <><div className="detail-title">{selectedEdge.sourceTable}.{selectedEdge.sourceField} <span>→</span> {selectedEdge.targetTable}.{selectedEdge.targetField}</div><div className="detail-grid"><div><span>SOURCE FIELD</span><b>{selectedEdge.sourceField} ({selectedEdge.sourceFieldId})</b></div><div><span>TARGET</span><b>{selectedEdge.targetTable}.{selectedEdge.targetField}</b></div><div><span>REVERSE FIELD</span><b>{selectedEdge.reverseField}</b></div><div><span>CONFIDENCE / PROVENANCE</span><b>{Math.round(selectedEdge.confidence * 100)}% · {selectedEdge.provenance}</b></div></div>{selectedEdge.source !== "ninox" && <p className="warning">Hypothesis: detected from scan evidence; not confirmed by Ninox metadata.</p>}</> : <p className="muted">Select a relationship to inspect its fields, confidence, and provenance.</p>}</div>
      </section></section><footer><span>Generated {data.generatedAt}</span><span>Data Mapper P0 · local artifact</span></footer>
  </main>;
}
